export const UNISWAP_V3_POOL_ABI = [
    {
        type: 'function',
        name: 'slot0',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            { name: 'sqrtPriceX96', type: 'uint160' },
            { name: 'tick', type: 'int24' },
            { name: 'observationIndex', type: 'uint16' },
            { name: 'observationCardinality', type: 'uint16' },
            { name: 'observationCardinalityNext', type: 'uint16' },
            { name: 'feeProtocol', type: 'uint8' },
            { name: 'unlocked', type: 'bool' },
        ],
    },
    {
        type: 'function',
        name: 'liquidity',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint128' }],
    },
    {
        type: 'function',
        name: 'token0',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        name: 'token1',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        name: 'fee',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint24' }],
    },
    {
        type: 'function',
        name: 'tickSpacing',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'int24' }],
    },
    {
        type: 'function',
        name: 'factory',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'event',
        name: 'Swap',
        inputs: [
            { name: 'sender', type: 'address', indexed: true },
            { name: 'recipient', type: 'address', indexed: true },
            { name: 'amount0', type: 'int256', indexed: false },
            { name: 'amount1', type: 'int256', indexed: false },
            { name: 'sqrtPriceX96', type: 'uint160', indexed: false },
            { name: 'liquidity', type: 'uint128', indexed: false },
            { name: 'tick', type: 'int24', indexed: false },
        ],
    },
    {
        type: 'event',
        name: 'Mint',
        inputs: [
            { name: 'sender', type: 'address', indexed: true },
            { name: 'owner', type: 'address', indexed: true },
            { name: 'tickLower', type: 'int24', indexed: true },
            { name: 'tickUpper', type: 'int24', indexed: true },
            { name: 'amount', type: 'uint128', indexed: false },
            { name: 'amount0', type: 'uint256', indexed: false },
            { name: 'amount1', type: 'uint256', indexed: false },
        ],
    },
    {
        type: 'event',
        name: 'Burn',
        inputs: [
            { name: 'owner', type: 'address', indexed: true },
            { name: 'tickLower', type: 'int24', indexed: true },
            { name: 'tickUpper', type: 'int24', indexed: true },
            { name: 'amount', type: 'uint128', indexed: false },
            { name: 'amount0', type: 'uint256', indexed: false },
            { name: 'amount1', type: 'uint256', indexed: false },
        ],
    },
] as const
